language: python

python:
  - "3.7-dev"

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - python -m pip install Pillow
  - pip install codecov

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - coverage run --source='.' manage.py test
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - export DJANGO_SETTINGS_MODULE=wonya.settings
  - python -m django_createsuperuser "WonyaAdmin" "myAdminPassword" wonya@admin.com

after_success:
  - codecov
