# Generated by Django 3.0.6 on 2020-05-28 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedCase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('urgency', models.CharField(max_length=200)),
                ('update', models.CharField(max_length=200)),
                ('incident_id', models.IntegerField(null=True)),
                ('hospital_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('vehicle_plate_no', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('responders_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.ReportedCase')),
            ],
        ),
    ]
