# Generated by Django 3.0.6 on 2020-06-09 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incident', '0011_auto_20200530_1327'),
        ('med_facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedCase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('urgency', models.CharField(max_length=200)),
                ('update', models.CharField(max_length=200)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='med_facility.MedicalFacility')),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.Incident')),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('vehicle_plate_no', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.ReportedCase')),
            ],
        ),
    ]
