# Generated by Django 3.0.6 on 2020-06-03 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responder',
            old_name='responders_id',
            new_name='case_id',
        ),
    ]
