# Generated by Django 3.0.6 on 2020-06-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20200603_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedcase',
            old_name='hospital_id',
            new_name='facility_id',
        ),
    ]
