# Generated by Django 3.0.6 on 2020-05-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injuries', models.PositiveIntegerField()),
                ('plateNumber', models.PositiveIntegerField()),
                ('prePlateCharacters', models.CharField(max_length=10)),
                ('postPlateCharacter', models.CharField(max_length=1)),
                ('sceneImage', models.ImageField(null=True, upload_to='media/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
