# Generated by Django 3.0.6 on 2020-05-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='sceneImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
