# Generated by Django 3.0.6 on 2020-05-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_auto_20200523_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='fatalities',
            field=models.PositiveIntegerField(),
        ),
    ]
