# Generated by Django 3.0.6 on 2020-05-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_auto_20200523_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='postPlateCharacter',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='prePlateCharacters',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
